language: node_js
sudo: false
node_js:
  - '0.12'
  - '4'
  - '5'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script: npm test
env:
  global:
    - DEBUG='* -superagent -express:* -mocha:*'
    - CXX=g++-4.8
before_install:
- openssl aes-256-cbc -K $encrypted_56217629029a_key -iv $encrypted_56217629029a_iv
  -in taskcluster-base-test.conf.json.enc -out taskcluster-base-test.conf.json -d

# encrpyt channel name to get around issue
# https://github.com/travis-ci/travis-ci/issues/1094
notifications:
  irc:
    channels:
      # encrpyted string was "irc.mozilla.org#taskcluster-bots"
      - secure: "VNI9CxF994rJEPArs8FIHYM0ndA1Sz29bhCjkUIwp2JztkGXtz1yi6fG4qvQCBBmoUeaj9bY+bXJ5nra+tMR74ZlopNtPGGCD4YUh2KR82MAELaLcTpIabFLN5WT5aWYwjl459HGba7HYh7NGjq3nh3KJdpjRDpSUrcxzjaErnz4ulmSYLCTXTohrOT8iX5Dic4O1vDdEyv8IvtWRgr5DtMJoyizig7h7CsF5DUZV6T74fPRm4O+eTHqe4jZHSZNqMizRHtzLUNIvbfLHE6T6eK0AtjhWn/dDbQLY0NMWAlqTEaJu1ujKduIZthxlq+kol8WtG4yF1axPamlEFjyObtpTbzNN1Yy0FURedqNa52XixRP1QOAJsIKkkdEB0BtlfJh+IEEn85JMzt8mIknmzZ1F9MGNr/lgPAD/fxaDDeEhwTHscGxoF/0Xc0sCjdc9heFzK2fS5QUAJblJxHJa04AX2QGFzNiN9JEy6ofs6gtiprvJ5ruMCgtKh1mnwaN6LAGP+xd5ZF3iKNW2ZvTFm3VKRoeUymp1D+XLfLNJIQy8+m+/lHXhnerpbnr0OUsXBXErjXGuyXRuNj8SbmHAVnBaGkfBept7gds3p0WKIMeEHy9PvBj8ba2/RvgoI/g51ZQwtWfnEwSZzyZ6wOmO6LtEfj/NW+HN5mAoSH8tBM="
    on_success: change
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      - "Commit message : %{commit_message}"
